# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package 5

on:
  push:
    tags:
      - "v*.*.*" # триггер на пуш тега вида v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 1st
        uses: actions/checkout@v4
        with:
          path: main
      - run: npm i -g -f corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pwd
      - run: pnpm i
      - run: pnpm build
      - name: 1st dir
        run: pwd

      - name: Checkout 2nd
        uses: actions/checkout@v4
        with:
          repository: m4rc0d3r/str-dist2
          path: secondary
      - name: 2nd dir
        run: |
          pwd
          ls -ali
          cd ..
          pwd
          ls -ali
